
import {
  Video,
  Monitor,
  Play,
  Camera,
  Mic,
  MicOff,
  Volume1,
  Volume2,
  VolumeX,
  Fullscreen,
  SkipBack,
  SkipForward,
  Pause,
  CirclePlay,
  CirclePause,
  Wifi,
  WifiOff,
  CircleCheck,
  CircleX,
  LogIn,
  LogOut,
  X,
  Copy,
  CameraOff,
} from "lucide-react";

export const Icons = {
  video: Video,
  monitor: Monitor,
  play: Play,
  camera: Camera,
  cameraOff: CameraOff,
  mic: Mic,
  micOff: MicOff,
  volume1: Volume1,
  volume2: Volume2,
  volumeX: VolumeX,
  fullscreen: Fullscreen,
  skipBack: SkipBack,
  skipForward: SkipForward,
  pause: Pause,
  circlePlay: CirclePlay,
  circlePause: CirclePause,
  wifi: Wifi,
  wifiOff: WifiOff,
  circleCheck: CircleCheck,
  circleX: CircleX,
  logIn: LogIn,
  logOut: LogOut,
  x: X,
  copy: Copy,
};